# Always color output
- arguments: [--color]

# Enable extra lint groups
- group: {name: future, enabled: true}
- group: {name: generalise-for-conciseness, enabled: true}
- group: {name: dollar, enabled: true}

# Require an export list for all modules other than Main
- warn: {name: Use module export list}
- ignore: {name: Use module export list, within: [Main]}

# Warn for redundant brackets with infix operators
- warn: {name: Redundant bracket due to operator fixities}
