# HLint configuration for yip - A very simple pre processor
# Copyright (C) 2023  Carter "pyrotelekinetic" Ison <carter@isons.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Always color output
- arguments: [--color]

# Enable extra lint groups
- group: {name: future, enabled: true}
- group: {name: generalise-for-conciseness, enabled: true}
- group: {name: dollar, enabled: true}

# Require an export list for all modules other than Main
- warn: {name: Use module export list}
- ignore: {name: Use module export list, within: [Main]}

# Warn for redundant brackets with infix operators
- warn: {name: Redundant bracket due to operator fixities}
